version: "3.7"
services:
    rabbitmq:
          image: rabbitmq:3-management-alpine
          container_name: rabbitmq
          volumes:
            - rabbitmq:/rabbitmq
          ports:
            - "15672:15672"
            - "5672:5672"
    logserver:
        image: datalust/seq:latest
        container_name: logserver
        ports:
            - "5341:80"
        environment:
            - ACCEPT_EULA=Y
    user-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: userservice
        ports:
            - "0.0.0.0:8081:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: sqlserver
        volumes:
            - sqlvolume:/var/opt/mssql
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "0.0.0.0:1433:1433"
volumes:
    rabbitmq:
        driver: local
    sqlvolume: