version: "3.7"
services:
    rabbitmq:
          image: rabbitmq:3-management-alpine
          container_name: rabbitmq
          volumes:
            - rabbitmq:/rabbitmq
          ports:
            - "15672:15672"
            - "5672:5672"
    logserver:
        image: datalust/seq:latest
        container_name: logserver
        ports:
            - "5341:80"
        environment:
            - ACCEPT_EULA=Y
    user-service:
        build:
            context: .
            dockerfile: Dockerfile_UserService
        container_name: userservice
        ports:
            - "0.0.0.0:8081:80"
volumes:
    rabbitmq:
        driver: local
    sqlvolume: