name: Build and release KweetService 

on:
  push:
    paths:
      - "KweetService/**"
      - ".github/workflows/KweetService.yml"

env:
  PROJECT_PATH: 'KweetService/KweetService.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: SonarScanner for .NET 5
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        sonarProjectKey: siebrum-kweet-service
        sonarProjectName: kwetter-kweet-service
        sonarOrganization: siebrum
        dotnetBuildArguments: ./KweetService
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: KweetService
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kwetter-image-service:latest